### ISSUE TITLE
syncthing-indicator not finding running syncthing instance

### ISSUE THREAD

**Issue by epe** [2nv2u/gnome-shell-extension-syncthing-indicator#27]
Hi! 
I'm getting this error every 20 seconds:
gnome-shell[115898]: [syncthing-indicator-manager:ERROR], Service failed to start, syncthing.service
gnome-shell[115898]: error: Syncthing Indicator: daemon-error

Unfortunately I cant find documentation about how the indicator expects synthing to be started?

I have configured syncthing to startup via systemd as described in the syncthing docs. 
./systemd/system/multi-user.target.wants/syncthing@username.service
./systemd/system/sleep.target.wants/syncthing-resume.service

what can I do to get it working together?

**Comment by 2nv2u** [comment]
Currently the extension uses the user config for systemd, I'll have a look on howto detect the system wide as well.

**Comment by doronbehar** [comment]
In my case I run syncthing as a system service and it's api key is located in `/var/lib/syncthing/.config/syncthing/config.xml` - not readable by any user. It would have been great if it was possible to specify the API key manually.

**Comment by 2nv2u** [comment]
I'll also see if I can create a preference section for settings like this, bare with me though.
I'm not having much time to work on this at the moment.

**Comment by leoherzog** [comment]
When following [the official instructions for installing Syncthing with systemd service](https://docs.syncthing.net/users/autostart.html#how-to-set-up-a-system-service), they recommend using
```sh
systemctl enable syncthing@myuser.service
```
which installs the service as the local user. This causes `gnome-shell-extension-syncthing-indicator` to be unable to see the running instance :(

**Comment by theCapypara** [comment]
@leoherzog read on one paragraph below that: https://docs.syncthing.net/users/autostart.html#how-to-set-up-a-user-service

The plugin only supports user services, otherwise it would need to have root permissions, which would be a giant security risk.

**Comment by 2nv2u** [comment]
Hi @leoherzog, @theCapypara is right, this plugin does not allow you to install the service globally and uses the [user section](https://docs.syncthing.net/users/autostart.html#how-to-set-up-a-user-service) instead.

If it doesn't exist in your local systemd config it will copy the [synthing.service](https://github.com/syncthing/syncthing/blob/main/etc/linux-systemd/user/syncthing.service) file into ~/.config/systemd/user folder and enables it with: `systemctl enable syncthing --user`. 

I might add something like these manual configurations as also requested for the API key in a extension config section though and disable the service buttons since you can't control them anymore as user.
Unfortunately I haven't gotten around to it yet.

**Comment by 2nv2u** [comment]
The extension was already capable of detecting if a system service was being used I've changed, but it did not take the syncthing@username.service into account, this has been fixed now.
