### ISSUE TITLE
Does not work on Pop!_OS 21.04

### ISSUE THREAD

**Issue by nourkagha** [2nv2u/gnome-shell-extension-syncthing-indicator#7]
Getting this error (on GNOME 3.38.4) repeatedly. The daemon is running and working fine.

![image](https://user-images.githubusercontent.com/50773468/127030979-5a2bd0c7-4e3c-452b-80e0-e9bf0e2052eb.png)

Let me know if you need any more information. Thank you!

**Comment by 2nv2u** [comment]
How are you running the daemon, installed it as system service?
This can happen if the service is not running in user space / uses the systemd script supplied with the extension.

**Comment by nourkagha** [comment]
Installed it as an apt package via the [Ubuntu repository](https://packages.ubuntu.com/hirsute/syncthing). Here is the output of `apt list syncthing`:

```
syncthing/hirsute,now 1.12.1~ds1-2 amd64 [installed]
```
I run the daemon through the 'Start Syncthing' desktop file via the application launcher. The desktop file has the following Exec path:

```
Exec=/usr/bin/syncthing -no-browser -logfile=default
```

**Comment by 2nv2u** [comment]
I think that that might be the problem, the syncthing indicator installs the systemd user service and that probably fails to start because the service was already started by you. Can you try to not start it yourself and see if that works?
Meanwhile I'll see if I can just disable the service controls when it detects an already running service...

**Comment by nourkagha** [comment]
> Can you try to not start it yourself and see if that works?

Tested this, does not work unfortunately. Gives the same error.

This has also only been an issue in 21.04. Worked fine in 20.10, even if I had manually started the daemon I believe.

**Comment by nourkagha** [comment]
**Update:** Removed Syncthing and installed it from the [PPA](https://apt.syncthing.net) (v1.18) rather than the [Ubuntu repository](https://packages.ubuntu.com/hirsute/syncthing) (v1.12). All works!

It seems the issue is only with 1.12.

**Comment by 2nv2u** [comment]
Great to hear and good find! I know what's really wrong then, since version 1.15 syncthing changed their systemd script and added serve to the ExecStart.
https://github.com/2nv2u/gnome-shell-extension-syncthing-indicator/blob/cd3d33c50b2c943f21903f97729523902341b511/src/syncthing.service#L8
This is unfortunately not backwards compatible...

**Comment by nourkagha** [comment]
Makes sense, thank you for investigating!

**Comment by sigg3** [comment]
Can confirm that using the syncthing PPA rather than distro repo works.
